### ISSUE TITLE
Consolidar BD entities

### ISSUE THREAD

**Issue by arturoaguileraa** [GDUMA/reservas-esqueleto#16]
Discutir por este Issue como vamos a distribuir las entidades de BBDD.

**Comment by tomgreef** [comment]
Algunas ideas entidades:

1. Clients
2. Administrators
3. Appointments
4. Products
5. Audits

**Comment by tomgreef** [comment]
**CLIENTS**
- id
- first_name
- last_name
- email
- password
- telephone

**Comment by tomgreef** [comment]
**ADMINISTRATORS**
- id
- first_name
- last_name
- email
- password

**Comment by tomgreef** [comment]
### PRODUCTS
- id
- name
- description
- duration
- price

**Comment by tomgreef** [comment]
APPOINTMENTS
- id
- date
- products
- client

**Comment by tomgreef** [comment]
### Audits
- user
- date
- action
- document

**Comment by tomgreef** [comment]
@GDUMA/grupo-2 que os parece?

**Comment by Naxetee** [comment]
Yo añadiría en **PRODUCTS** += *units available*
 "         "       "  **APPOINTMENTS** += *start/end time* (aunque a lo mejor esto está dentro de *date*)

**Comment by Naxetee** [comment]
Además, no entiendo muy bien cuál es la diferencia entre las **AUDITS** y los **APPOINTMENTS**

**Comment by tomgreef** [comment]
@Naxetee y yo hemos debatido esto y vamos comentarlo con todos en la próxima reunión ✌💪
