### ISSUE TITLE
¿Cómo vamos a editar/eliminar citas?

### ISSUE THREAD

**Issue by tomgreef** [GDUMA/reservas-esqueleto#17]
Lo he pensado, y creo que quizas como estamos haciendo unas reservas, que podrían solo crear, ver y eliminarlas. Ya que si dejamos que lo actualizen va haber mucho conflicto con otras citas. Es decir, se le va presentar las mismas opciones como si la crease de nuevo. 

Por ello, **propongo** que cuando trabajamos en el interfaz/vista de lista de citas, que mostremos una lista de las previas citas y las que tenga pendientes, y estas últimas tendran un boton con la opción de eliminar. Y si quisiesen cambiar de fecha o tiempo tendrán que hacer una cita nueva (o llamar al local en la vida real, pero esto es muy personalizado, por ello creo que debemos quitar el update)

**Comment by Naxetee** [comment]
Bajo mi punto de vista, intentaría crear una vista sólo para la actualización de citas, donde te deje modificar tan sólo la hora y el día, no veo por qué esto puede crear conflicto. Es cierto que en el back end, la acción de actualizar una cita puede resolverse eliminandola y creando una nueva a partir de los datos de la anterior cambiando únicamente la fecha y/o hora. Podemos intentarlo y en el caso en que no salga, podemos hacer lo que ha propuesto @tomgreef. Pero creo que queda muy bien que exista una opción de actualizar una cita.

**Comment by tomgreef** [comment]
@Naxetee y yo hemos debatido esto y vamos comentarlo con todos en la próxima reunión ✌💪
