### ISSUE TITLE
Preparación para la siguiente fase

### ISSUE THREAD

**Issue by tomgreef** [GDUMA/reservas-esqueleto#18]
Ya sabéis que espero terminar diseño en 2 semanas, y por ello os quiero preparar para la siguiente fase que sería implementación. En la reunión de hoy hemos acordado algunas cosas, pero os comento aquí:

### Expectativas
- Usar MongoDB para alojar base de datos y netlify para front-end ReactJS
- Aprender MERN stack que incluye (MongoDB, Express, ReactJS, NodeJS)
- Lenguages de programación usadas: NoSQL, Javascript, HTML, CSS

### Nueva idea
- Usar Google Firebase para alojar base de datos y autentificar usuarios, con netlify para front-end ReactJS
- Aprender full-stack con Google Firebase (fácil manejo) y ReactJS (incluyendo Typescript)
- Lenguages de programación usadas: NoSQL, Javascript, TypeScript, HTML, CSS

Por favor, comentar las ideas y opiniones que tengáis, y si algo os suena chino buscarlo rápido en google y sino preguntais.

### Finalemente
**La aportación de recursos** puedo hacerlo yo para que todos leáis del mismo sitio, o podéis hacerlo vosotros independientemente. Dejo que decidáis con una reacción a ese primer comentario: Tom aporta con 🎉, yo busco con 🚀. Por mayoría eligimos ✌ Luego, aquí dos enlaces a cursos de udemy que tenemos 3 de nosotros, por si queréis preparar (dándole más importancia al primero!):

- https://www.udemy.com/course/aprende-react-firebase-2021-actualizado/?couponCode=54E81E866BDE74013A73
- https://www.udemy.com/course/typescript-2020/?couponCode=966B2DBFD2DE35C29670

**Comment by arturoaguileraa** [comment]
Yo he reaccionado con un 🚀 porque estoy intentando buscar un poco por mi cuenta y además creo que si cada uno busca por su cuenta el aprendizaje es mucho más ampliado ya que no se ajusta a un solo cursillo, pero si preferis lo otro tampoco le pongo muchas pegas..

**Comment by Naxetee** [comment]
Yo opino que todos podemos compartir lo que leemos, así tenemos más alcance.

**Comment by tomgreef** [comment]
Pues concluido este issue, todo el mundo se busca sus recursos para la siguiente fase (implementación) y lo compartís por el canal de Feed de Discord 🚀💪
