### ISSUE TITLE
Clase: User

### ISSUE THREAD

**Issue by tomgreef** [GDUMA/reservas-esqueleto#19]
Esto sería una super clase de Administrator y Client. Con los valores que tendrían estos dos en común.

**Comment by tomgreef** [comment]
Reaccionar con emojis 💪

**Comment by arturoaguileraa** [comment]
Hey reabro este issue para preguntar y proponer una cosilla. ¿Qué funciones creéis que deben tener en común los Users? Yo he pensado tanto en getters como en setters de name, password y email. Tenéis pensado alguna más? Creeis que no se deben de poner algunas funciones que he comentado? Decidmeee y parad de beber cerveza todoss

**Comment by arturoaguileraa** [comment]
También como esta es la clase padre de client y de admin estaría bien también proponer que funciones puede hacer un cliente y cuales puede un admin 🍻

**Comment by tomgreef** [comment]
Buen comentario, en principio en la última reunión dijimos de que todas las clases van tener los getters y setters de sus atributos. Luego, como funciones adicionales para la clase User diría:

1. createAppointment()
2. deleteAppointment (Appointment Id)
3. modifyAppointment (Appointment Id)
4. modifyUser()

Luego para los dos por separado:
**Admin**

1. createProduct
2. editProduct (Product Id)
3. deleteProduct (Product Id)
4. createAdmin
5. deleteAdmin

**Client**

1. modifyUser() // Incluye número telefono

Eso es lo que me ocurre ahora, y dentro de las funciones "modify" usaríamos las funciones de setters por ejemplo. Porque lo que nos permitirá esta función es añadir validación cuando se hace una modificación. Es decir, la función _modifyUser(Attributos)_ primero ejecutará una función que sería "validación(Attributos)" (por ejemplo), y devuelve un boolean si se ha efectuado correctamente o no. En caso de no haber pasado la validación, sería un False, en caso de que pase la validación pasaría a usar los setters y devolvería un True.
