### ISSUE TITLE
Requisitos Funcionales

### ISSUE THREAD

**Issue by tomgreef** [GDUMA/reservas-esqueleto#2]
Nuestro sistema dispone ahora mismo de los siguientes "rols": Clientes, Administrador, Gerente y Empleado. Pero siguiendo el modelo de reservas, podemos suponer que el administrador va ser a la vez el Gerente o empleado. ¿Os parece bien si en la documentación solo hacemos CRUD de Clientes, Administrador, Citas y Productos? De esta forma simplificamos el sistema, y en un futuro podríamos crear distintos clases de un interfaz para los roles.

**Comment by tomgreef** [comment]
**¿Y como registramos a los administradores?**
Tenemos que considerar que el administrador tendrá que iniciar session y tendrá la posibilidad de modificar varios datos. Pero en general sería una subclase del cliente.

**Comment by tomgreef** [comment]
Vale, me parece una buena propuesta! Lo añado a requisitos y lo doy por listo!

**Comment by Naxetee** [comment]
Está perfecto, simplemente decir que hay algunas faltas de ortografía, pero es comprensible. Durante la próxima reunión podemos leerlo juntos y corregirlas en un momento.

**Comment by fraaaandelpino** [comment]
Me parece perfecto que el primer admin se registre en la BD y ya vaya creando este admin a nuevos admins.

**Comment by tomgreef** [comment]
@Naxetee podrías cambiarlo o especificar que exactamente?

**Comment by arturoaguileraa** [comment]
Tom, me parece que está muy bien y muy claro! Pero te comento lo mismo que Naxetee, hay alguna que otra falta de ortografía. Te recomiendo hacer un PR para que le pueda hacer una review y que te sea más fácil poder corregirlas.

**Comment by tomgreef** [comment]
Voy hacer el pull request ahora 💪
