### ISSUE TITLE
Button - Botón

### ISSUE THREAD

**Issue by Naxetee** [GDUMA/reservas-esqueleto#20]
No sé muy bien si lo que he hecho es la idea que se tiene, ¿cómo lo veis?. Creo que deberíamos escoger fuentes de texto ya, para tenerlas ahí y que no añada cada uno la suya.

**Comment by tomgreef** [comment]
He revisado el botón, y lo veo bien. Solo comentaría lo siguiente:

1. Creo que estaría bien poner el texto en "**bold**", ya que es dificil de ver lo que pone en el texto exactamente.
2. No estoy seguro si has copiado ese botón como un componente o lo has creado de 0, pero para simplifacar la forma de la figura donde esta el texto, podrías haber creado un rectángulo solo y ajustar los parámetros de los bordes.
![image](https://user-images.githubusercontent.com/33311803/113830811-44779980-9787-11eb-9e12-80907cf4d24f.png)

Voy a ponerte un ejemplo debajo de la tuya, y ya tu decides.

Finalmente, la tipografía ya está mas o menos definida de la librería de "Essential Components UI......" , porque cuando creas un texto y le cambias el texto a H1 o H4, ya estás usando la misma tipografía que los demás.

**Comment by tomgreef** [comment]
Además de eso, es importante que rellenes la metadata de los issues que creas, para la mejor gestion de nuestro repositorio 💪

**Comment by Naxetee** [comment]
Todo perfecto. Sí, cree la forma con un rectángulo y dos círculos, no vi la opción de los bordes.
Cierto, olvidé rellenar el issue, srry.

**Comment by tomgreef** [comment]
No worries, tu aprendes de mí, yo aprendo de tí 🌀
