### ISSUE TITLE
¿Qué vistas debemos diseñar?

### ISSUE THREAD

**Issue by Naxetee** [GDUMA/reservas-esqueleto#22]
Ayudadme a hacer una lista con todas las vistas que hay que diseñar:
- Home
- Login + Registro
- Perfil
- Modificar Perfil
- Perfil Admin
- Ajustes (Admin)
- Hacer una Reserva
- Lista de reservas
- Tablón de Anuncios
- ...

**Comment by arturoaguileraa** [comment]
Yo te diría las siguientes:

- Home (sin logear)
- Login
- Registro
- Homepage (User)
- Homepage (Admin)
- Mi Perfil/Modificar perfil (creo que va a ir en la misma vista)
- Lista de mis reservas (User)
- Gestionar de reservas (Admin)
- Hacer una Reserva/Modificar una reserva (User y Admin)
- Lista de servicios de la empresa (Admin)
- Crear Servicio/Modificar servicio (Admin)
- Tablón de Anuncios (¿Esto se va a llevar a cabo?)

Luego quizás hay algún derivado de estas vistas

**Comment by arturoaguileraa** [comment]
Quizás las vistas que he puesto en barras (Ej. Crear Servicio/Modificar servicio) se tienen que duplicar para poder trabajar bien en código pero a lo que me refiero es que el diseño es el mismo.

**Comment by Naxetee** [comment]
Todas las vistas están terminadas, damos por finalizado el proceso de diseño.
