### ISSUE TITLE
Requisitos - Introducción

### ISSUE THREAD

**Issue by tomgreef** [GDUMA/reservas-esqueleto#4]

**Comment by tomgreef** [comment]
He añadido algunos comentarios en el pull request.

**Comment by arturoaguileraa** [comment]
He leido lo tuyo y las recomendaciones de Tom en el pull request y nada más que añadir, lo veo de lujo.

**Comment by Naxetee** [comment]
¿Debería cambiar yo lo que tú me sugieres, o lo haces tú directamente @tomgreef ?

**Comment by tomgreef** [comment]
Es tu sección! Mejor que lo cambies tu y estés a cargo de la revision. Luego, cierra este issue y trabajamos desde el Pull Request solo. Buen trabajo 💪🍻

**Comment by Naxetee** [comment]
Procedo a cerrar el issue ya que todos los problemas y dudas ya han sido resueltas.
