### ISSUE TITLE
Requisitos - Diseño e implementación

### ISSUE THREAD

**Issue by arturoaguileraa** [GDUMA/reservas-esqueleto#5]
¿Qué pensáis que deberíamos poner del 4.5.2?

**Comment by arturoaguileraa** [comment]
Finalmente una vez hablado con @tomgreef he reflejado en que servidores se va a desarrollar nuestro software tanto en back/front como en la BBDD.

**Comment by tomgreef** [comment]
Yo creo que lo comentado esta genial como primer enfoque, y que podríamos cambiarlo cuando lleguemos a implementación.
