### ISSUE TITLE
Requisitos - Vista General del Producto

### ISSUE THREAD

**Issue by manu23manuel** [GDUMA/reservas-esqueleto#7]
Varias dudas:

El punto 2.3 (restricciones), no tengo que restricciones vamos a tener en cuenta ya que esto no tiene un fin destinado claro.
2.5 Nosotros no dependemos de nada, no?

**Comment by Naxetee** [comment]
**En el punto 2.3** pienso que puedes mencionar que vamos a usar la interfaz de diseño **MVC** *(Modelo, Vista, Controlador)*, además de ***Singleton***, ya que las entiendo como restricciones a la hora de programar el producto. Además puedes añadir que el producto cumplirá con los estándares del ***IEEE*** y que respetará la ***Ley de Protección de Datos***.

De hecho, en general, puedes poner que el producto final ***Reservas-Esqueleto*** es una interfaz en sí misma. De forma que cuando alguien la use para desarrollar su propia aplicación de reservas para un tema más concreto, tendrá que amoldarse a esta implementación.

Eso con respecto a los puntos ***Interfaces***, ***Restricciones de diseño*** y ***Cumplimiento de Normas***. Con respecto a ***Restricciones de calidad***, yo añadiría lo siguiente:

> *El servidor que soporte el sistema deberá ser capaz de atender múltiple peticiones simultáneas, es decir, permitirá concurrencia, controlando que en ningún momento interfieran unas con otras y se proporcionen datos incorrectos. Debe garantizarse la seguridad del servidor mediante sistemas de encriptación y autenticación para los usuarios que tengan posibilidad de modificar la base de datos.*

---

**En el punto 2.5**, no estoy muy seguro, pero entiendo que nosotros, al adoptar un *método en cascada* para trabajar, no sabemos los problemas que tendremos en la programación hasta que no lleguemos a ella. Además, cómo este método no permite la marcha atrás, el ***SRS*** no deberá modificarse una vez acabemos la fase ***Documentación***. Por tanto, en este apartado pondría:

> **2.5 Suposiciones y dependencias**
>  *Dependencias no descritas*

**Comment by tomgreef** [comment]
Haz un pull request de esto 🙏
