### ISSUE TITLE
Requisitos - Requisitos No Funcionales

### ISSUE THREAD

**Issue by jann9** [GDUMA/reservas-esqueleto#8]
¿Alguien tiene alguna recomendación en cuanto a los tiempos de respuesta y restricciones de tiempo del apartado 4.3.1?

**Comment by Naxetee** [comment]
He buscado en un ejemplo de SRS de gestión hotelera (que es muy similar a la aplicación web que estamos desarrollando) y he encontrado lo siguiente en ese campo:
>**Requisitos de Rendimiento**
>+ La mayoría de las peticiones al sistema deberán servirse en menos de dos segundos.
>+ El sistema deberá estar disponible las 24 horas del día.
>+ Cuando el rendimiento decaiga por debajo del 70% de su capacidad total restringirá el acceso de nuevas peticiones hasta que se liberen recursos para atender nuevas peticiones.
>+ El sistema gestor de bases de datos procesará el 90% de las transacciones en menos de cinco segundos.
>+ Las tarjetas de red utilizadas deberán ser de 10/100 Mbps

No se si es justamente lo que queremos nosotros pero puede orientarte sobre que poner ahí.

**Comment by jann9** [comment]
Muchas gracias me ayuda bastante la verdad

**Comment by tomgreef** [comment]
Pull request porfas 🙏

**Comment by jann9** [comment]
Estoy liado con el apartado 4.4, que no tengo muy claro que es  lo que hay que poner

**Comment by tomgreef** [comment]
Podrías definir algunos formatos, es decir, _las franjas disponibles serán de 15 minutos_. No se me ocurren muchas cosas, pero eso es la idea creo. Aún así podrías dejarlo en blanco y lo rellenamos en un futuro, puede que no todas secciones sean aplicables a nuestra APP 💪
